### ISSUE TITLE
Replace fmt.Println() with logger.Print()

### ISSUE THREAD

**Issue by binhonglee** [binhonglee/GlobeTrotte#215]
1. Add import `"github.com/binhonglee/GlobeTrotte/src/turbine/logger"` to the target file.
2. Find all use of `fmt.Print()` and `fmt.Println()` in the file and replace them with `logger.Print()`. (The syntax of `logger.Print()` requires a `Namespace` which can be found [here](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/logger/namespaces.go). Namespace should be the package name of where its called.)
3. Check the BUILD file of the package (the one in the same folder) and make sure that its `deps` include `"//src/turbine/logger:logger"`.
4. Submit your PR!

Example:
- [src/turbine/database/db.go](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/database/db.go#L13)
- [src/turbine/database/BUILD](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/database/BUILD#L13)

Files to change
- [x] [src/turbine/database/tripdb.go](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/database/tripdb.go)
- [x] [src/turbine/database/userdb.go](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/database/userdb.go)
- [x] [src/turbine/router/handlers.go](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/router/handlers.go)
- [x] [src/turbine/router/structhandlers.go](https://github.com/binhonglee/GlobeTrotte/blob/main/src/turbine/router/structhandlers.go)

_Note: Don't worry about making the change in all the files in a single PR. Feel free to submit PR for change on just a single file. All help is appreciated. Thanks!_

**Comment by an0nn30** [comment]
PR submitted.

**Comment by binhonglee** [comment]
This is now fixed. Closing...
